export { default as Navbar } from './navbar/navbar'
export { default as Footer } from './footer/footer'
export { default as Carousel } from './carousel/carousel'
export { default as ParticlesBg } from './particles-bg/particles-bg'
export { default as useGetList } from './hooks/useGetList'
export { default as useGetDetails } from './hooks/useGetDetails'
export { default as Loader } from './loader/loader'
export { default as ProfileCard } from './card/card'
export { default as Title } from './title/title'
export { default as MostViewed } from './most-viewed/most-viewed'
export { domainsData } from './constants/constants'
